spring:

  application:
    name: hacaton_05_04_2024

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:hacaton_2}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
    hibernate:
      ddl-auto: validate

  liquibase:
    default-schema: ${POSTGRES_SCHEMA:public}
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
    contexts: hacaton

